### ISSUE TITLE
Not compatible with PHP 8.x

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/focal_point#3]
Using PHP8 focal_point breaks BD with this error notice:
TypeError: in_array(): Argument #2 ($haystack) must be of type array, null given in in_array() (line 637 of /mypath/modules/focal_point/focal_point.module).

**Comment by robertgarrigos** [comment]
I'm using it with php8.1 with no problem. Not this one, at least. Does this still apply?

**Comment by laryn** [comment]
This looks like it was probably an issue with your local configuration. Default configuration should not cause a problem here. 

Please reopen if you continue to experience this.
