### ISSUE TITLE
Focal point test drive not working

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/focal_point#4]
The focal point test drive page (/focal_point/test-drive) doesn't show the image to test. Also, a page not found error message gets triggered (/files/styles/focal_point_preview/public)

**Comment by laryn** [comment]
@robertgarrigos I have requested to be added as a maintainer here and am waiting on that to be approved. In the meantime, if you are able, could you test the PR that is linked here? It should fix a variety of issues at once, including this one and the jQuery 3.x issue you filed.

**Comment by robertgarrigos** [comment]
Thanks, @laryn. Sorry for the late answer.
