### ISSUE TITLE
Not working with JQuery 3

### ISSUE THREAD

**Issue by robertgarrigos** [backdrop-contrib/focal_point#5]
This module is not working with JQuery 3. It does with JQuery 1.
Editing a node with an image field which uses focal point triggers this error:

```
jquery.js?v=3.7.1:2 Uncaught TypeError: Cannot read properties of undefined (reading 'indexOf')
    at ce.fn.load (jquery.js?v=3.7.1:2:82864)
    at HTMLImageElement.<anonymous> (focal_point.js:44:23)
    at Function.each (jquery.js?v=3.7.1:2:3129)
    at ce.fn.init.each (jquery.js?v=3.7.1:2:1594)
    at focal_point.js:42:14
```

**Comment by laryn** [comment]
I think this is working on the latest code -- please reopen if not.

**Comment by robertgarrigos** [comment]
Still, I'm getting this error in the web console with jQuery 3 and the latest code.

With jQuery 3 the cross in the image always appears in the top-left corner of the image. Only when I switch to jquery 1 the cross appears where you left it the last time.

![Edita_Notícia_Dia_Internacional_d_Acció_per_a_la_Salut_de_les_Dones___Ona_Codinenca_-_Vivaldi](https://github.com/user-attachments/assets/cabdb1b8-4f2b-4333-bf3a-8b4988502373)

**Comment by robertgarrigos** [comment]
I think I've found the problem here: https://blog.jquery.com/2015/07/13/jquery-3-0-and-jquery-compat-3-0-alpha-versions-released/

I've fixed this problem by changing this code:

```
setTimeout(function() {
          $img.one('load', function(){
            focalPointSetIndicator($indicator, $(this), $field);
          }).each(function() {
            if (this.complete) {
              $(this).load();
            }
          });
        }, 0);
```

to this:

```
setTimeout(function () {
          $img.one('load', function () {
            focalPointSetIndicator($indicator, $(this), $field);
          }).each(function () {
            if (this.complete) {
              $(this).trigger('load'); // Trigger the load event manually if the image is already loaded
            }
          });
        }, 0);
```

**Comment by robertgarrigos** [comment]
Done a PR which addresses this problem.

**Comment by laryn** [comment]
@robertgarrigos Is this working for you with the latest version? At some point the same change you suggest must have been added -- it doesn't seem like your PR changes anything substantial.

**Comment by robertgarrigos** [comment]
@laryn yes, latest version works with jQuery 3. Thanks
