### ISSUE TITLE
Add @laryn as a maintainer

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/focal_point#6]
I would like to test this out but see issues for PHP 8.x and jQuery 3.x compatibility. I am willing to be added as a maintainer as I'm testing to try to see if I can get things working and make a new release.

**Comment by klonos** [comment]
Thanks @laryn :pray: ...there is no maintainer listed currently indeed, so I'm fine with expediting this. Out of courtesy though, @herbdool since you seem to have done the initial port, can you please concur?

**Comment by herbdool** [comment]
Awesome @laryn. You have my blessing

**Comment by klonos** [comment]
Tis done! 🙂 ...thank you both @laryn and @herbdool 🙏🏼
